system:
  version: 3
  debug: false
  language: 'en'
  updates:
    channel: 'bukkit' #can be dev, stable-dev, bukkit
    notification: true
    time: 1h #the amount of time between checks for an update, while we are in betas it will be low but when out of beta it will be every 11 hours
  useBukkitTimer: true
storage:
  type: 'flatfile' #can be flatfile, sqlite, or mysql
  mysql:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'password'
    database: 'jailDatabase'
    prefix: 'j3_'
jailing:
  during:
    blockBreakPenalty: 5m
    blockBreakProtection: true
    blockBreakWhiteList: ['crops', 'carrot', 'potato'] # these blocks can be broken at any time by prisoners
    blockPlacePenalty: 5m
    blockPlaceProtection: true
    blockPlaceWhiteList: ['crops', 'carrot', 'potato'] # these blocks can be placed at any time by prisoners
    cellsign:
    - '%player%'
    - '%timeinminutes% mins'
    - 'with a reason'
    - '%reason%'
    commandPenalty: 5m
    commandProtection: true
    commandWhitelist: ['/ping', '/list', '/jail status', '/jail pay']
    countDownTimeWhileOffline: false
    cropTramplingPenalty: 5m
    cropTramplingProtection: true
    foodControl:
      enabled: true
      max: 20
      min: 10
    ignoreSleeping: true
    maxAFKTime: 10m #in minutes
    movePenalty: 10m
    moveProtection: true
    openChest: true
    preventInteractionBlocks: ['wooden_door', 'iron_door_block']
    preventInteractionBlocksPenalty: 5m
    preventInteractionItems: []
    preventInteractionItemsPenalty: 5m
    recieveMessages: true
    scoreboard:
      enabled: false
      title: 'Jail Info'
      time: '&aTime:'
  jail:
    automaticCell: true
    automaticMute: true
    broadcastJailing: false
    clothing:
      enabled: true
      helmet: leather_helmet~175,105,33
      chest: leather_chestplate~175,105,33
      legs: leather_leggings~175,105,33
      boots: leather_boots~175,105,33
    commands: []
    default:
      jail: nearest #the jail nearest to the player
      time: 30m #default the time to 30 minutes, if no time
    gameMode: adventure
    inventory:
      blacklist: [] #items they aren't allowed to keep
      store: true
    log:
      console: true
      profile: true
  release:
    backToPreviousPosition: false
    commands: []
    restorePreviousGameMode: false
    teleport: true
jails:
  endermenProtection: true
  explosionProtection: true
jailpay:
  enabled: true
  item: air
  pricePerMinute: 1.5
  priceInfinite: 10000
jailstick:
  enabled: true
  sticks: ["stick,30m,,Running away,-1", "blaze_rod,15m,,Having too much fun,6"]